version: '3'

services:

  node:
    image: alandutra1982/node:prod
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s sh -c "npm install && node index.js"
    volumes:
      - ./node:/usr/src/app
    networks:
      - node-nginx-network
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx:   
    image: alandutra1982/nginx:prod
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks: 
      - node-nginx-network
    ports:
      - "8080:80"
    depends_on:
      - node

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0 # sempre é necessário aplicar esse comando
    container_name: db
    restart: always # se o container cair restarta o container
    tty: true
    volumes:
      #- /mysql:/var/lib/mysql
      - ./node/.docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-nginx-network 

networks:
  node-nginx-network:
    driver: bridge

